title: prithvs
remote_theme: jekyll/minima
minima:
  skin: dark
header_pages:
  - works.md
  - about.md
  - articles.md
  - notes.md
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
